# Specify Base Image
FROM node:18-alpine
 
# Work Directory
WORKDIR /usr/app

#Copy the app files into the working directory
COPY ./ ./
 
# Install Dependencies
RUN npm install
 
# Startup Command
CMD ["npm", "run", "serve"]